init_d_script.patch application

diff --git a/etc/init.d/omniorb-eventservice.in b/etc/init.d/omniorb-eventservice.in
--- a/etc/init.d/omniorb-eventservice.in
+++ b/etc/init.d/omniorb-eventservice.in
@@ -15,14 +15,22 @@
 ### BEGIN INIT INFO
 # Provides: omniorb-eventservice
 # Required-Start: $syslog $network
+# Should-Start: $omniorb-namingservice
 # Required-Stop: $syslog
-# Default-Start: 3 4 5
-# Default-Stop: 0 1 2 6
+# Should-Stop: $omniorb-namingservice
+# Default-Start:
+# Default-Stop: 0 1 2 3 4 5 6
 # Short-Description: CORBA event service
 # Description: CORBA event service. http://www.omnievents.org/
 ### END INIT INFO
 
+# Defaults for chkconfig in case LSB fails
+# chkconfig: - 91 09
+
 # ---------------------- the real stuff starts here----------------------------
+
+# Source function library.
+. /lib/lsb/init-functions
 
 # You might want to tweak the location of the configuration file:
 CONFIGFILE=@SYSCONFIG_DIR@/omniorb-eventservice
@@ -49,26 +57,47 @@ test -n "$OMNIEVENTS_ALTERNATE" && OPT_ALTERNATE="-a $OMNIEVENTS_ALTERNATE"
 test -n "$OMNIEVENTS_NS_NAME"   && OPT_NS_NAME="-N $OMNIEVENTS_NS_NAME"
 
 startOE() {
+  local RC
+
+  # Make sure the naming service is available
+  /usr/bin/nameclt list > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    log_failure_msg "omniEvents cannot reach the naming service"
+    exit 1
+  fi
+
   test -d $OMNIEVENTS_LOGDIR || mkdir -p $OMNIEVENTS_LOGDIR
-  printf "Starting $DESC on port $OMNIEVENTS_PORT: "
   $DAEMON $OMNIEVENTS_OPTIONS -P $OMNIEVENTS_PIDFILE -l $OMNIEVENTS_LOGDIR \
-    -p $OMNIEVENTS_PORT $OPT_ALTERNATE $OPT_NS_NAME
-  echo "$NAME."
+    -p $OMNIEVENTS_PORT $OPT_ALTERNATE $OPT_NS_NAME > /dev/null 2>&1
+  RC=$?
+  [ "$RC" -ne 0 ] && log_failure_msg $"Starting $NAME" || log_success_msg $"Starting $NAME"
+  return $RC
 }
 
-# If omniEvents is running, then send it SIGTERM and wait for
-# up to 6 seconds for it to delete its PID file.
 stopOE() {
-  if [ -f $OMNIEVENTS_PIDFILE ] ; then
-    printf "Stopping $DESC: "
-    kill `cat $OMNIEVENTS_PIDFILE` || rm -f $OMNIEVENTS_PIDFILE 2>/dev/null
-    t=0
-    while test -f $OMNIEVENTS_PIDFILE -a $t -lt 6 ; do
-      sleep 1
-      t=`expr $t + 1`
-    done
-    echo "$NAME."
+  local RC
+  if [ ! -f $OMNIEVENTS_PIDFILE ] ; then
+    return 0
   fi
+
+  killproc -p $OMNIEVENTS_PIDFILE $NAME
+  RC=$?
+  [ "$RC" -ne 0 ] && log_failure_msg $"Stopping $NAME" || log_success_msg $"Stopping $NAME"
+  return $RC
+}
+
+rh_status() {
+    # run checks to determine if the service is running or use generic status
+    status $NAME
+}
+
+rh_status_q() {
+    rh_status >/dev/null 2>&1
+}
+
+restart() {
+    stopOE
+    startOE
 }
 
 case "$1" in
@@ -105,9 +134,13 @@ case "$1" in
         echo "Not implemented."
         exit 3
         ;;
+  condrestart)
+        rh_status_q || exit 0
+        restart
+        ;;
   *)
-        N=@INSTALL_ETC@/init.d/omniorb-eventservice
-        echo "Usage: $N {start|stop|restart|status}" >&2
+        N=/etc/init.d/omniorb-eventservice
+        echo "Usage: $N {start|stop|restart|condrestart|status}" >&2
         exit 1
         ;;
 esac
